# SPDX-FileCopyrightText: {{cookiecutter.year}} {{cookiecutter.author_name}} <{{cookiecutter.author_email}}>
#
# SPDX-License-Identifier: {{cookiecutter.license}}


# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: reuse
    name: reuse
    description:
      "Lint the project directory for compliance with the REUSE Specification"
    language: system
    entry: poetry run reuse lint
    pass_filenames: false

  - id: pycln
    name: pycln
    description:
      "A formatter for finding and removing unused import statements."
    language: system
    entry: poetry run pycln
    types: [python]

  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: poetry run mypy
    types: [python]
    require_serial: true

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: poetry run pytest
    types: [python]
    pass_filenames: false

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: poetry run pytest --cov --cov-fail-under=100
    types: [python]
    pass_filenames: false
